# Generated by Django 3.2.18 on 2024-04-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adocao_cachorro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adocao_cachorro.doador')),
            ],
        ),
    ]
